name: Build

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS
            os: macos-latest
            build_type: Release
          - name: Windows
            os: windows-latest
            build_type: Release

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure
        run: >
          cmake
          -S .
          -B build
          -DVOX_BUILD_APPS=OFF
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} --parallel 2

      - name: Test
        run: ctest --test-dir build --build-config ${{ matrix.build_type }} --output-on-failure
